apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik 
      version: "10.6.0"
      sourceRef:
        kind: HelmRepository
        name: traefik 
        namespace: ingress
      interval: 1m
  values:
    ssl:
      insecureSkipVerify: true
    service:
      externalIPs:
      - 45.151.166.29
